version: '3.1'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: code200!
      POSTGRES_DB: MTBL
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
