# Define on 20200803 to initialize 3 node kubernetes cluster

Vagrant.configure("2") do |config|
  # Define image
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true
#   config.ssh.username = "nopaws"
#   config.ssh.password = "code200!"

# Define Jenkins Worker Node
  config.vm.define "jenkins", autostart: true do |node|
    node.vm.box = "ubuntu/focal64"
    node.vm.provider "virtualbox" do |vb|
      vb.name = "Jenkins"
      vb.memory = 2048
      vb.cpus = 2
    end

    node.vm.hostname = "jenkins"
    node.vm.network "private_network", ip: "192.168.56.60"
    node.vm.network "forwarded_port", guest: 22, host: "5522", auto_correct: true
    node.vm.provision :shell, :path => "bootstrap.sh"
  end

end
