# Generated by Django 3.2 on 2021-12-27 14:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_restaurantmodel_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('current_date', models.DateField(default=django.utils.timezone.now)),
                ('vote_count', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='RestaurantModel',
            new_name='Restaurant',
        ),
        migrations.DeleteModel(
            name='FoodMenuModel',
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.restaurant'),
        ),
    ]
